apiVersion: v1
kind: Service
metadata:
  name: financial-monitor-api-service
  labels:
    app: financial-monitor
    component: api
spec:
  type: ClusterIP
  selector:
    app: financial-monitor
    component: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
